### PR TITLE
update CI toolchain

### PR DESCRIPTION
**Pull request by pauloacmartinez**

### CODE REVIEW

**Comment by pacm93** [comment]
This PR is still WIP, as I need to debug the CI.

**Comment by pacm93** [comment]
The PR is done from my side.

**Comment by claremacrae** [comment]
Hello @pacm93  could you explain the purpose of the changes to the .gitmodules file, which now uses relative paths? Does it have any impact for people cloning or forking this repo? 

Naively, not knowing much about modules, it looks to me like it would require someone to clone both the referenced repos, and put them in very specific locations ... 

And how does that relate to updating the CI toolchain?

Thanks.

**Comment by pauloacmartinez** [comment]
Hello @claremacrae, relative submodule paths makes mirroring the project and its submodules painless, while maintaining the clone/fork experience unaltered. Regarding the CI, it has been red since 7615eefb849056a5d9ad54bc9158d0fcb48d9683 due to some old distros. I upgraded them and also added newer compiler versions.

**Comment by claremacrae** [comment]
Hi @pauloacmartinez - thanks, that's really useful to know!

**Comment by krzysztof-jusiak** [comment]
thanks @pauloacmartinez

**Pull request merged**
